FROM python:slim

WORKDIR /app

COPY . /app/

RUN pip install geocoder
RUN pip install django
RUN pip install folium
RUN pip install pandas
RUN pip install geopy

EXPOSE  8000

CMD python manage.py runserver --noreload 0.0.0.0:8000