FROM python:slim

WORKDIR /app

COPY . /app/


RUN pip install geocoder
RUN pip install django
RUN pip install folium
RUN pip install pandas

EXPOSE  80

CMD ["python","manage.py","runserver","--noreload"]